# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9c9afb0d4165d7b0e2045605b204d625"
name = "adec-dev-app"
handle = "adec-dev-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false

[build]
include_config_on_deploy = true

[api]
api_version = "2024-10"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,read_draft_orders,read_orders,write_orders,read_products,write_products,read_customers,write_customers,read_inventory,write_inventory"

[auth]
redirect_urls = [
  "https://shopify.dev/apps/default-app-home/api/auth",
  "https://adec-shopify-dev-app.netlify.app/.netlify/functions/oauth-callback",
]

[app_proxy]
prefix = "apps"
subpath = "create-draft-order"
url = "https://adec-shopify-dev-app.netlify.app/.netlify/functions/create-draft-order"